# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Requestum' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Requestum
  pod 'R.swift'

end
